import Header from './Header'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Layout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <main className={`min-h-screen flex flex-col bg-base-100`}>
        <Header />
        {children}
    </main>
  )
}
